### ISSUE TITLE
Fatal error in CiviCRM 4.7.8

### ISSUE THREAD

**Issue by twomice** [JMAConsulting/civicrm_address_geocode#4]
After upgrading to CiviCRM 4.7.8 (from 4.6.9), a view that relies on this module reports this error:

Fatal error: Call to undefined method CRM_Core_BAO_CustomField::buildOption() in [Drupal_root]/sites/all/modules/civicrm_address_geocode/civicrm_address_geocode_handler_filter_practice_areas.inc on line 18

Interested in a fix?

**Comment by JoeMurray** [comment]
PRs very welcome!
