### ISSUE TITLE
All geocodes deleted on disable, thus breaks in CiviCRM upgrade

### ISSUE THREAD

**Issue by twomice** [JMAConsulting/civicrm_address_geocode#6]
To reproduce:
1. Find or create a Views page with search filters that allow searching by proximity to a zip code (not sure if there are other ways to reproduce this).  Set and apply filter criteria, and observe that results are returned.
2. Upgrade CiviCRM according to standard procedure.
3. Repeat step 1, and observe that no results are returned.

What appears to be happening:
1. CiviCRM upgrade procedure is to disable all CiviCRM-related modules before upgrading, and re-enable them afterwards.
2. Upon disabling this module, the geocode fields are deleted (https://github.com/JMAConsulting/civicrm_address_geocode/blob/master/civicrm_address_geocode.module#L66), thus deleting all the data they contain.
3. Upon re-enabling this module, the geocode fields are recreated, but not repopulated.
4. As a result, immediately after a CiviCRM upgrade, geocode-based searches will return zero results.

As a workaround, after the upgrade, run code like this to repopulate all geocode proximity data for existing addresses:

```
civicrm_initialize();
$address = new CRM_Core_DAO_Address();
$address->whereAdd("ifnull(geo_code_1, '') > ''");
$address->whereAdd("ifnull(geo_code_2, '') > ''");
$address->find();
while ($address->fetch()) {
  updateGeoCode($address);
}
```

**Comment by JoeMurray** [comment]
Edsel, deleting data for an extension/module is appropriate for uninstall but not for disable. Could you move this to an appropriate hook?

Thx.
